// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: model.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2020 Bret Taylor

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Sensor {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: UInt32 = 0

  var latitude: Float = 0

  var longitude: Float = 0

  var aqi10M: UInt32 = 0

  var aqi30M: UInt32 = 0

  var aqi1H: UInt32 = 0

  var aqi6H: UInt32 = 0

  var aqi24H: UInt32 = 0

  var lastUpdated: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Sensors {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var sensors: [Sensor] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "data"

extension Sensor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Sensor"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "latitude"),
    3: .same(proto: "longitude"),
    4: .standard(proto: "aqi_10m"),
    5: .standard(proto: "aqi_30m"),
    6: .standard(proto: "aqi_1h"),
    7: .standard(proto: "aqi_6h"),
    8: .standard(proto: "aqi_24h"),
    9: .standard(proto: "last_updated"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.latitude) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.longitude) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.aqi10M) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.aqi30M) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.aqi1H) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.aqi6H) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.aqi24H) }()
      case 9: try { try decoder.decodeSingularUInt64Field(value: &self.lastUpdated) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularUInt32Field(value: self.id, fieldNumber: 1)
    }
    if self.latitude != 0 {
      try visitor.visitSingularFloatField(value: self.latitude, fieldNumber: 2)
    }
    if self.longitude != 0 {
      try visitor.visitSingularFloatField(value: self.longitude, fieldNumber: 3)
    }
    if self.aqi10M != 0 {
      try visitor.visitSingularUInt32Field(value: self.aqi10M, fieldNumber: 4)
    }
    if self.aqi30M != 0 {
      try visitor.visitSingularUInt32Field(value: self.aqi30M, fieldNumber: 5)
    }
    if self.aqi1H != 0 {
      try visitor.visitSingularUInt32Field(value: self.aqi1H, fieldNumber: 6)
    }
    if self.aqi6H != 0 {
      try visitor.visitSingularUInt32Field(value: self.aqi6H, fieldNumber: 7)
    }
    if self.aqi24H != 0 {
      try visitor.visitSingularUInt32Field(value: self.aqi24H, fieldNumber: 8)
    }
    if self.lastUpdated != 0 {
      try visitor.visitSingularUInt64Field(value: self.lastUpdated, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sensor, rhs: Sensor) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.latitude != rhs.latitude {return false}
    if lhs.longitude != rhs.longitude {return false}
    if lhs.aqi10M != rhs.aqi10M {return false}
    if lhs.aqi30M != rhs.aqi30M {return false}
    if lhs.aqi1H != rhs.aqi1H {return false}
    if lhs.aqi6H != rhs.aqi6H {return false}
    if lhs.aqi24H != rhs.aqi24H {return false}
    if lhs.lastUpdated != rhs.lastUpdated {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sensors: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Sensors"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "sensors"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.sensors) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sensors.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.sensors, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sensors, rhs: Sensors) -> Bool {
    if lhs.sensors != rhs.sensors {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
